<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>DrawThatThing.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="2.88.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DrawThatThing.Platform\DrawThatThing.Platform.csproj" />
  </ItemGroup>

</Project>
